### ISSUE TITLE
Port existing benchmark logic

### ISSUE THREAD

**Issue by markerikson** [reduxjs/react-redux-benchmarks#1]
Since https://github.com/reduxjs/react-redux/pull/1008 was reverted, we should start out by copying the entire `benchmarks` folder over to the root of this repo to start off.

**Comment by cellog** [comment]
done. @markerikson @timdorr 

Next, I'm going to extract the fps-emitter code into a private package we can import into each benchmark

**Comment by cellog** [comment]
done. now we can make beautiful new benchmark babies

**Comment by markerikson** [comment]
Okay, I'd say this is taken care of.
