### ISSUE TITLE
Results?

### ISSUE THREAD

**Issue by Slapbox** [reduxjs/react-redux-benchmarks#18]
It would be awesome to have some sample results in this repo!

**Comment by markerikson** [comment]
What exactly are you looking for?

If you want to see some of the output format and some representative numbers, see here:

https://github.com/reduxjs/react-redux/issues/1177#issuecomment-464406021

**Comment by Slapbox** [comment]
That's exactly what I'm looking for! Thanks a ton!

It might be worth linking to that from the ReadMe for people who are looking for some quick numbers without installing anything.
